openapi: 3.0.0
info:
  title: IT
  description: "API for user login, registration, post & comment in social network."
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/duytnuniversity/social-network-api/1.0.0
  description: SwaggerHub API Auto Mocking
paths: {}
components: {}
